import json
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from typing import Dict, Any, List, Optional
import google.generativeai as genai
from pydantic import BaseModel, ValidationError

class QuizQuestionSchema(BaseModel):
    question_text: str
    options: List[str]
    correct_answer_index: int
    explanation: str
    context_page_number: Optional[int] = None
    context_snippet: Optional[str] = None

from backend.config import settings
from backend.models.paper import Chunk
from backend.models.quiz import Quiz, QuizQuestion

class QuizGeneratorService:
    def __init__(self):
        genai.configure(api_key=settings.GEMINI_API_KEY)
        self.model = genai.GenerativeModel(settings.GEMINI_MODEL)

    async def generate_quiz(self, db: AsyncSession, paper_id: str) -> Quiz:
        import uuid
        paper_uuid = uuid.UUID(paper_id)
        
        # 1. Fetch chunks from the database
        stmt = select(Chunk).where(Chunk.paper_id == paper_uuid).order_by(Chunk.page_number, Chunk.id)
        result = await db.execute(stmt)
        chunks = result.scalars().all()

        if not chunks:
            raise ValueError("No text chunks found for this paper.")

        # Construct the context payload (Limit context if necessary, but gemini 1.5 pro handles 1M+ tokens)
        context_blocks = []
        for chunk in chunks:
            context_blocks.append(f"--- Page {chunk.page_number} ---\n{chunk.text_content}")
            
        full_context = "\n\n".join(context_blocks)

        # 2. Define the JSON schema prompt
        prompt = (
            "You are an expert academic evaluator. Based on the provided research paper excerpts, "
            "generate a rigorous multiple-choice quiz testing deep technical comprehension.\n"
            "Generate exactly 5 questions.\n"
            "Return the output STRICTLY as a raw JSON object with the following schema, and absolutely no other text or markdown blocks:\n"
            "{\n"
            '  "title": "A concise title for the quiz",\n'
            '  "questions": [\n'
            "    {\n"
            '      "question_text": "The question",\n'
            '      "options": ["Option A", "Option B", "Option C", "Option D"],\n'
            '      "correct_answer_index": 0, // integer 0-3\n'
            '      "explanation": "Why this answer is correct",\n'
            '      "context_page_number": 1, // the page number where the answer is found\n'
            '      "context_snippet": "A short exact quote from the paper proving the answer"\n'
            "    }\n"
            "  ]\n"
            "}\n\n"
            f"PAPER TEXT:\n{full_context}"
        )

        # 3. Generate content
        from starlette.concurrency import run_in_threadpool
        response = await run_in_threadpool(
            self.model.generate_content,
            prompt,
            generation_config=genai.GenerationConfig(
                response_mime_type="application/json"
            )
        )

        
        # 4. Parse response and store in DB
        try:
            quiz_data = json.loads(response.text)
        except json.JSONDecodeError:
            raise ValueError("Failed to parse the LLM output as JSON.")

        import logging
        logger = logging.getLogger(__name__)

        quiz = Quiz(
            paper_id=paper_uuid,
            title=quiz_data.get("title", "Generated Quiz")
        )
        db.add(quiz)
        await db.flush() # flush to get quiz.id

        questions = []
        for q_data in quiz_data.get("questions", []):
            try:
                valid_q = QuizQuestionSchema.model_validate(q_data)
                question = QuizQuestion(
                    quiz_id=quiz.id,
                    question_text=valid_q.question_text,
                    options=valid_q.options,
                    correct_answer_index=valid_q.correct_answer_index,
                    explanation=valid_q.explanation,
                    context_page_number=valid_q.context_page_number,
                    context_snippet=valid_q.context_snippet
                )
                questions.append(question)
            except ValidationError as e:
                logger.warning(f"Skipping invalid question: {e}")
            
        if not questions:
            raise ValueError("No valid questions were generated by the LLM.")
            
        db.add_all(questions)
        await db.commit()
        await db.refresh(quiz)

        return quiz
