import React, { useState, useEffect } from 'react';
import { API_BASE, getChatHistory, saveChatHistory } from '../../api';
import { Loader2, Send, FileText } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import 'katex/dist/katex.min.css';

interface SynthesisFeedProps {
  paperId: string;
  onCitationClick: (page: number, chunkIndex: number) => void;
}

interface Source {
  page_number: number;
  chunk_index: number;
  text: string;
}

interface HistoryEntry {
  id?: string;
  query: string;
  answer: string;
  sources: Source[];
}

export default function SynthesisFeed({ paperId, onCitationClick }: SynthesisFeedProps) {
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(false);
  const [history, setHistory] = useState<HistoryEntry[]>([]);
  const [initialLoading, setInitialLoading] = useState(true);

  useEffect(() => {
    getChatHistory(paperId)
      .then(data => {
        setHistory(data);
      })
      .catch(console.error)
      .finally(() => setInitialLoading(false));
  }, [paperId]);

  const handleQuery = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim()) return;
    
    const currentQuery = query;
    setLoading(true);
    setQuery('');
    
    // Create a temporary history entry that we will update in-place
    const tempEntryIndex = history.length;
    // Use functional state update to ensure we have the latest history length if multiple renders happen
    setHistory(prev => [...prev, { query: currentQuery, answer: "", sources: [] }]);
    
    try {
      const response = await fetch(`${API_BASE}/rag/query`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ paper_id: paperId, query: currentQuery, top_k: 5 }),
      });
      
      if (!response.ok) throw new Error('Failed to fetch answer');
      
      const reader = response.body?.getReader();
      if (!reader) throw new Error('ReadableStream not supported');
      
      const decoder = new TextDecoder('utf-8');
      let done = false;
      let currentAnswer = "";
      let currentSources: Source[] = [];
      let accumulatedData = "";

      while (!done) {
        const { value, done: readerDone } = await reader.read();
        done = readerDone;
        if (value) {
          accumulatedData += decoder.decode(value, { stream: true });
          const lines = accumulatedData.split('\n\n');
          accumulatedData = lines.pop() || "";
          
          for (const line of lines) {
            if (line.startsWith('data: ')) {
              const dataStr = line.substring(6);
              try {
                const data = JSON.parse(dataStr);
                if (data.type === 'sources') {
                  currentSources = data.sources;
                  setHistory(prev => {
                    const newHist = [...prev];
                    newHist[prev.length - 1].sources = currentSources;
                    return newHist;
                  });
                } else if (data.type === 'token') {
                  currentAnswer += data.content;
                  setHistory(prev => {
                    const newHist = [...prev];
                    newHist[prev.length - 1].answer = currentAnswer;
                    return newHist;
                  });
                } else if (data.type === 'error') {
                   throw new Error(data.error);
                } else if (data.type === 'done') {
                  done = true;
                  break;
                }
              } catch (e) {
                if (e instanceof Error && e.message !== "Unexpected end of JSON input") {
                    throw e; // rethrow real errors
                }
                // Ignore JSON parse errors for incomplete chunks just in case
              }
            }
          }
        }
      }
      
      // Save to database
      try {
        await saveChatHistory(paperId, currentQuery, currentAnswer, currentSources);
      } catch (err) {
        console.error("Failed to save chat history to DB");
      }
      
    } catch (err: any) {
      setHistory(prev => {
        const newHist = [...prev];
        newHist[prev.length - 1].answer = "Failed to retrieve an answer: " + err.message;
        return newHist;
      });
    } finally {
      setLoading(false);
    }
  };

  /** Render plain markdown since inline citations are no longer generated by the model */
  const renderAnswerWithCitations = (text: string) => {
    return (
      <ReactMarkdown 
        remarkPlugins={[remarkMath]}
        rehypePlugins={[rehypeKatex]}
        components={markdownComponents}
      >
        {text}
      </ReactMarkdown>
    );
  };

  /** Custom component overrides to style rendered markdown within the dark theme */
  const markdownComponents = {
    h1: ({ children, ...props }: any) => <h1 className="text-lg font-semibold text-zinc-100 mt-5 mb-2 leading-tight" {...props}>{children}</h1>,
    h2: ({ children, ...props }: any) => <h2 className="text-base font-semibold text-zinc-100 mt-4 mb-2 leading-tight" {...props}>{children}</h2>,
    h3: ({ children, ...props }: any) => <h3 className="text-sm font-semibold text-zinc-200 mt-3 mb-1.5 uppercase tracking-wide" {...props}>{children}</h3>,
    p: ({ children, ...props }: any) => <p className="text-sm text-zinc-300 leading-relaxed mb-3" {...props}>{children}</p>,
    ul: ({ children, ...props }: any) => <ul className="list-disc list-outside pl-5 mb-3 space-y-1" {...props}>{children}</ul>,
    ol: ({ children, ...props }: any) => <ol className="list-decimal list-outside pl-5 mb-3 space-y-1" {...props}>{children}</ol>,
    li: ({ children, ...props }: any) => <li className="text-sm text-zinc-300 leading-relaxed" {...props}>{children}</li>,
    strong: ({ children, ...props }: any) => <strong className="font-semibold text-zinc-100" {...props}>{children}</strong>,
    em: ({ children, ...props }: any) => <em className="italic text-zinc-400" {...props}>{children}</em>,
    hr: (props: any) => <hr className="border-zinc-800 my-4" {...props} />,
    blockquote: ({ children, ...props }: any) => <blockquote className="border-l-2 border-zinc-700 pl-3 my-3 text-sm text-zinc-400 italic" {...props}>{children}</blockquote>,
    code: ({ children, className, ...props }: any) => {
      const isInline = !className;
      return isInline
        ? <code className="bg-zinc-800 text-emerald-400 px-1.5 py-0.5 rounded text-xs font-mono" {...props}>{children}</code>
        : <code className={`block bg-zinc-900 rounded-lg p-4 text-xs font-mono text-zinc-300 overflow-x-auto my-3 ${className || ''}`} {...props}>{children}</code>;
    },
  };

  return (
    <div className="flex flex-col h-full">
      <h2 className="text-xl font-semibold mb-4 tracking-tight text-zinc-100">Synthesis Feed</h2>
      
      <div className="flex-1 overflow-y-auto pr-2 mb-4 space-y-5">
        {history.length === 0 && !loading && (
          <div className="flex flex-col items-center justify-center h-full text-center opacity-50">
            <FileText size={32} className="text-zinc-600 mb-3" />
            <p className="text-sm text-zinc-500">Ask a question about the paper.<br/>The AI will synthesize an answer from relevant sections.</p>
          </div>
        )}

        {history.map((entry, i) => (
          <div key={i} className="space-y-3">
            {/* User query bubble */}
            <div className="flex justify-end">
              <div className="bg-zinc-800 border border-zinc-700 rounded-xl rounded-br-sm px-4 py-2.5 max-w-[85%]">
                <p className="text-sm text-zinc-200">{entry.query}</p>
              </div>
            </div>
            
            {/* AI answer card */}
            <div className="bg-zinc-900/60 border border-zinc-800 rounded-xl rounded-bl-sm p-5">
              {entry.answer === "" && loading && i === history.length - 1 ? (
                <div className="flex items-center gap-3">
                  <Loader2 size={16} className="animate-spin text-zinc-500" />
                  <span className="text-sm text-zinc-500">Synthesizing from paper context…</span>
                </div>
              ) : (
                <div className="prose-sm">
                  {renderAnswerWithCitations(entry.answer)}
                </div>
              )}
              
              {entry.sources.length > 0 && (
                <div className="mt-4 pt-3 border-t border-zinc-800">
                  <h4 className="text-[10px] font-mono text-zinc-600 uppercase tracking-widest mb-2">Referenced Sources</h4>
                  <div className="flex flex-wrap gap-1.5">
                    {entry.sources.map((src, j) => (
                      <button
                        key={j}
                        onClick={() => onCitationClick(src.page_number, src.chunk_index)}
                        className="inline-flex items-center gap-1 px-2 py-1 rounded text-[10px] font-mono bg-zinc-800 text-zinc-400 border border-zinc-700/50 hover:text-zinc-200 hover:border-zinc-600 transition-colors cursor-pointer"
                        title={src.text.substring(0, 100)}
                      >
                        <FileText size={9} />
                        p.{src.page_number} §{src.chunk_index}
                      </button>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        ))}


      </div>

      <form onSubmit={handleQuery} className="mt-auto relative">
        <input
          type="text"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Ask a question about this paper…"
          className="w-full bg-zinc-900 border border-zinc-800 rounded-xl py-3 pl-4 pr-12 text-sm text-white placeholder-zinc-600 focus:outline-none focus:border-zinc-600 focus:ring-1 focus:ring-zinc-700 transition-all"
        />
        <button 
          type="submit" 
          disabled={loading || !query.trim()}
          className="absolute inset-y-1.5 right-1.5 px-3 bg-zinc-800 text-zinc-400 rounded-lg hover:bg-zinc-700 hover:text-zinc-200 disabled:opacity-30 transition-colors flex items-center justify-center"
        >
          {loading ? <Loader2 size={14} className="animate-spin" /> : <Send size={14} />}
        </button>
      </form>
    </div>
  );
}
